### PR TITLE
Remove unnecessary heap allocations and calls to C.

### PR DESCRIPTION
**Pull request by koponen-styra**
Instead of allocating the function name and function parameter/return
value holders for each function invocation, pre-allocate them. This is
possible because invocations occur sequentially (in presence of no
threading).

This both reduces GC pressure and removes two cgo calls.

### CODE REVIEW

**Comment by koponen-styra** [comment]
Hmm, "just test" passes locally on my ubuntu. I tried to access the details from bors, but it merely says permission denied.

**Comment by syrusakbary** [comment]
I think bors failed because some Github permissions. Let's try again

bors r+

**Comment by syrusakbary** [comment]
The error seem to be in the test bazel build:

```
Run export GOOS=$(go env GOHOSTOS)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   612  100   612    0     0   2571      0 --:--:-- --:--:-- --:--:--  2571

100 6028k  100 6028k    0     0  10.7M      0 --:--:-- --:--:-- --:--:-- 10.7M
2020/02/19 10:09:15 could not resolve the version 'latest' to an actual version number: could not get releases from github.com/bazelbuild/bazel: could not download list of Bazel releases from github.com/bazelbuild: unexpected status code while reading https://api.github.com/repos/bazelbuild/bazel/releases: 403
##[error]Process completed with exit code 1.
```

**Comment by syrusakbary** [comment]
@koponen-styra if you rebase your PR with the latest master, the issue should be fixed (via https://github.com/wasmerio/go-ext-wasm/commit/351f7724b4934da92afc4d0e82a1cba4517ce0c1 )

**Pull request merged**
